import React, { useEffect, useState } from 'react'
import { ExternalLink, RefreshCw } from 'lucide-react'
import { useNOCStore } from '../../store/nocStore'
import { api } from '../../api/client'
import { StatusBadge, Card, CardHeader, EmptyState, Spinner } from '../shared/ui'
import { formatDistanceToNow } from 'date-fns'

const priorityColor: Record<string, string> = {
  'P1 - Critical': 'text-red-400 bg-red-950/30 border-red-600',
  'P2 - High': 'text-orange-400 bg-orange-950/30 border-orange-600',
  'P3 - Memo': 'text-yellow-400 bg-yellow-950/30 border-yellow-600',
  'P4 - Info': 'text-blue-400 bg-blue-950/30 border-blue-600',
}

export default function TicketsPage() {
  const { tickets, setTickets } = useNOCStore()
  const [loading, setLoading] = useState(false)
  const [stats, setStats] = useState<any>(null)
  const [selected, setSelected] = useState<any>(null)
  const [filterStatus, setFilterStatus] = useState('ALL')

  const load = async () => {
    setLoading(true)
    try {
      const [t, s] = await Promise.all([api.tickets.list(), api.tickets.stats()])
      setTickets(t)
      setStats(s)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  const filtered = filterStatus === 'ALL' ? tickets : tickets.filter(t => t.status === filterStatus)

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-white">JIRA Tickets</h1>
          <p className="text-sm text-gray-400">Auto-generated by NOC AI Ticketing Agent</p>
        </div>
        <button onClick={load} className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-gray-700 text-gray-300 hover:bg-gray-800 text-sm transition-colors">
          <RefreshCw size={14} /> Refresh
        </button>
      </div>

      {/* Stat pills */}
      {stats && (
        <div className="flex gap-3 flex-wrap">
          {[
            { label: 'Total', value: stats.total, color: 'bg-gray-800 text-gray-300 border-gray-700' },
            { label: 'Open', value: stats.open, color: 'bg-blue-950/40 text-blue-300 border-blue-700' },
            { label: 'In Progress', value: stats.in_progress, color: 'bg-purple-950/40 text-purple-300 border-purple-700' },
            { label: 'Resolved', value: stats.resolved, color: 'bg-green-950/40 text-green-300 border-green-700' },
          ].map(s => (
            <div key={s.label} className={`flex items-center gap-2 px-3 py-1.5 rounded-full border text-sm font-medium ${s.color}`}>
              <span className="font-bold">{s.value}</span>
              <span className="text-xs opacity-70">{s.label}</span>
            </div>
          ))}
        </div>
      )}

      <div className="flex gap-2">
        {['ALL', 'Open', 'In Progress', 'Resolved'].map(s => (
          <button key={s}
            onClick={() => setFilterStatus(s)}
            className={`px-3 py-1.5 rounded-lg text-sm transition-colors ${
              filterStatus === s ? 'bg-blue-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
            }`}>{s}</button>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <div className="xl:col-span-2">
          <Card>
            {loading ? <Spinner /> : (
              <div className="divide-y divide-gray-800">
                {filtered.map(ticket => (
                  <div key={ticket.jira_key}
                    onClick={() => setSelected(ticket)}
                    className="p-4 hover:bg-gray-800/30 cursor-pointer transition-colors">
                    <div className="flex items-start gap-3">
                      <span className={`shrink-0 px-2 py-0.5 rounded border text-xs font-bold ${priorityColor[ticket.priority] ?? 'text-gray-400 bg-gray-800 border-gray-600'}`}>
                        {ticket.priority?.split(' - ')[0] ?? 'P?'}
                      </span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-xs text-blue-400 font-bold shrink-0">{ticket.jira_key}</span>
                          <StatusBadge status={ticket.status} />
                        </div>
                        <p className="text-sm text-white mt-1 truncate">{ticket.title}</p>
                        <div className="flex items-center gap-3 mt-1">
                          <span className="text-xs text-gray-500">Reporter: {ticket.reporter}</span>
                          <span className="text-xs text-gray-600">
                            {formatDistanceToNow(new Date(ticket.created_at), { addSuffix: true })}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
                {filtered.length === 0 && <EmptyState message="No tickets yet — alarms will auto-generate tickets" />}
              </div>
            )}
          </Card>
        </div>

        {/* Ticket detail */}
        <Card>
          <CardHeader title="Ticket Detail" subtitle={selected?.jira_key ?? 'Select a ticket'} />
          {selected ? (
            <div className="p-4 space-y-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className={`px-2 py-0.5 rounded border text-xs font-bold ${priorityColor[selected.priority] ?? ''}`}>
                    {selected.priority}
                  </span>
                  <StatusBadge status={selected.status} />
                </div>
                <h3 className="text-white text-sm font-semibold leading-snug">{selected.title}</h3>
              </div>
              <div className="space-y-2 text-xs">
                {[
                  ['JIRA Key', selected.jira_key],
                  ['Reporter', selected.reporter ?? 'NOC AI Agent'],
                  ['Assignee', selected.assignee ?? 'Unassigned'],
                  ['Created', new Date(selected.created_at).toLocaleString()],
                ].map(([k, v]) => (
                  <div key={k} className="flex justify-between">
                    <span className="text-gray-500">{k}</span>
                    <span className="text-gray-200">{v}</span>
                  </div>
                ))}
              </div>
              {selected.description && (
                <div className="border-t border-gray-800 pt-3">
                  <p className="text-xs text-gray-500 mb-2">Description</p>
                  <pre className="text-xs text-gray-300 whitespace-pre-wrap font-sans leading-relaxed max-h-64 overflow-y-auto">
                    {selected.description}
                  </pre>
                </div>
              )}
              <div className="flex gap-2 border-t border-gray-800 pt-3">
                {['Open', 'In Progress', 'Resolved'].map(s => (
                  <button key={s}
                    onClick={async () => {
                      await api.tickets.updateStatus(selected.jira_key, s)
                      setSelected({ ...selected, status: s })
                    }}
                    className={`flex-1 py-1.5 rounded text-xs transition-colors border ${
                      selected.status === s
                        ? 'bg-blue-600 border-blue-500 text-white'
                        : 'bg-gray-800 border-gray-700 text-gray-400 hover:bg-gray-700'
                    }`}>{s}</button>
                ))}
              </div>
            </div>
          ) : <EmptyState message="Click a ticket to view details" />}
        </Card>
      </div>
    </div>
  )
}
